///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NewsModelTopicInfo {
/*
{
  "topicId": 8,
  "topicName": "dịch bệnh"
}
*/

  int? topicId;
  String? topicName;

  NewsModelTopicInfo({
    this.topicId,
    this.topicName,
  });
  NewsModelTopicInfo.fromJson(Map<String, dynamic> json) {
    topicId = json['topicId']?.toInt();
    topicName = json['topicName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['topicId'] = topicId;
    data['topicName'] = topicName;
    return data;
  }
}

class NewsModel {
/*
{
  "newsId": 5,
  "name": "Thông tin TP.HCM dùng 5 trực thăng phun khử khuẩn là sai sự thật",
  "description": "Lãnh đạo Sở TT&TT TP.HCM cho biết, thông tin dùng 5 trực thăng phun khử trùng diệt Covid-19 là sai...",
  "officialRating": "real",
  "publisher": null,
  "content": "Theo Sở TT&TT, hiện nay, trên mạng xã hội đang lan truyền thông tin “tối nay từ 11h40 không nên ra đường. Cửa ra vào và cửa sổ nên được đóng lại khi 5 máy bay trực thăng phun chất khử trùng vào không khí để diệt trừ Coronavirus”. Trao đổi với VietNamNet, ông Lâm Đình Thắng, Giám đốc Sở TT&TT cho hay, Bộ Tư lệnh TP.HCM khẳng định, thông tin trên hoàn toàn sai sự thật. Lực lượng quân đội phun khử khuẩn trên địa bàn TP.HCM Trước đó, sáng 23/7, Bộ Tư lệnh TP.HCM phối hợp với Lữ đoàn 87 Binh Chủng hóa học, Tiểu đoàn Phòng hóa 38 Quân khu 7 cùng với lực lượng vũ trang TP và 21 quận, huyện và TP Thủ Đức đồng loạt mở đợt cao điểm phun thuốc khử khuẩn phòng, chống dịch Covid-19 quy mô lớn nhất từ trước tới nay trên địa bàn TP, trong thời gian 7 ngày. Mỗi ngày sẽ có 20 lượt xe tham gia phun thuốc khử khuẩn phòng, chống Covid-19. Theo Hồ Văn/Báo điện tử VietnamNet https://vietnamnet.vn/vn/thoi-su/thong-tin-tp-hcm-dung-5-truc-thang-phun-khu-khuan-la-sai-su-that-759937.html",
  "thumbNews": "newid5.jpg",
  "status": 1,
  "timestamp": "2021-12-15T13:37:45.14139",
  "languageId": "vi",
  "topicInfo": [
    {
      "topicId": 8,
      "topicName": "dịch bệnh"
    }
  ]
}
*/

  int? newsId;
  String? name;
  String? description;
  String? officialRating;
  String? publisher;
  String? content;
  String? thumbNews;
  int? status;
  String? timestamp;
  String? languageId;
  List<NewsModelTopicInfo?>? topicInfo;

  NewsModel({
    this.newsId,
    this.name,
    this.description,
    this.officialRating,
    this.publisher,
    this.content,
    this.thumbNews,
    this.status,
    this.timestamp,
    this.languageId,
    this.topicInfo,
  });
  NewsModel.fromJson(Map<String, dynamic> json) {
    newsId = json['newsId']?.toInt();
    name = json['name']?.toString();
    description = json['description']?.toString();
    officialRating = json['officialRating']?.toString();
    publisher = json['publisher']?.toString();
    content = json['content']?.toString();
    thumbNews = json['thumbNews']?.toString();
    status = json['status']?.toInt();
    timestamp = json['timestamp']?.toString();
    languageId = json['languageId']?.toString();
    if (json['topicInfo'] != null) {
      final v = json['topicInfo'];
      final arr0 = <NewsModelTopicInfo>[];
      v.forEach((v) {
        arr0.add(NewsModelTopicInfo.fromJson(v));
      });
      topicInfo = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['newsId'] = newsId;
    data['name'] = name;
    data['description'] = description;
    data['officialRating'] = officialRating;
    data['publisher'] = publisher;
    data['content'] = content;
    data['thumbNews'] = thumbNews;
    data['status'] = status;
    data['timestamp'] = timestamp;
    data['languageId'] = languageId;
    if (topicInfo != null) {
      final v = topicInfo;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['topicInfo'] = arr0;
    }
    return data;
  }
}
