///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NewsModelTopicInfo {
/*
{
  "topicId": 1,
  "topicName": "afghanistan"
}
*/

  int? topicId;
  String? topicName;

  NewsModelTopicInfo({
    this.topicId,
    this.topicName,
  });
  NewsModelTopicInfo.fromJson(Map<String, dynamic> json) {
    topicId = json['topicId']?.toInt();
    topicName = json['topicName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['topicId'] = topicId;
    data['topicName'] = topicName;
    return data;
  }
}

class NewsModel {
/*
{
  "languageId": "en",
  "newsId": 4,
  "title": "Hospitalizations of Americans under 50 have reached new pandemic highs",
  "content": "A lagging vaccination campaign and the spread of the highly contagious Delta variant are driving a surge in Covid-19 hospitalizations in the United States..",
  "url": "https://www.independent.co.uk/arts-entertainment/eurovision/the-rasmus-eurovision-2022-finland-b2077365.html",
  "alias": "a-lagging-vaccine",
  "thumbNews": "http://localhost:5001/images/news/newsid4.jpg",
  "officialRating": null,
  "viewCount": 6,
  "publisher": null,
  "timestamp": "2022-05-16T12:47:00.157796",
  "status": 1,
  "topicInfo": [
    {
      "topicId": 1,
      "topicName": "afghanistan"
    }
  ]
}
*/

  String? languageId;
  int? newsId;
  String? title;
  String? content;
  String? url;
  String? alias;
  String? thumbNews;
  String? officialRating;
  String? viewCount;
  String? publisher;
  String? timestamp;
  int? status;
  List<NewsModelTopicInfo?>? topicInfo;

  NewsModel({
    this.languageId,
    this.newsId,
    this.title,
    this.content,
    this.url,
    this.alias,
    this.thumbNews,
    this.officialRating,
    this.viewCount,
    this.publisher,
    this.timestamp,
    this.status,
    this.topicInfo,
  });
  NewsModel.fromJson(Map<String, dynamic> json) {
    languageId = json['languageId']?.toString();
    newsId = json['newsId']?.toInt();
    title = json['title']?.toString();
    content = json['content']?.toString();
    url = json['url']?.toString();
    alias = json['alias']?.toString();
    thumbNews = json['thumbNews']?.toString();
    officialRating = json['officialRating']?.toString();
    viewCount = json['viewCount']?.toString();
    publisher = json['publisher']?.toString();
    timestamp = json['timestamp']?.toString();
    status = json['status']?.toInt();
    if (json['topicInfo'] != null) {
      final v = json['topicInfo'];
      final arr0 = <NewsModelTopicInfo>[];
      v.forEach((v) {
        arr0.add(NewsModelTopicInfo.fromJson(v));
      });
      topicInfo = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['languageId'] = languageId;
    data['newsId'] = newsId;
    data['title'] = title;
    data['content'] = content;
    data['url'] = url;
    data['alias'] = alias;
    data['thumbNews'] = thumbNews;
    data['officialRating'] = officialRating;
    data['viewCount'] = viewCount;
    data['publisher'] = publisher;
    data['timestamp'] = timestamp;
    data['status'] = status;
    if (topicInfo != null) {
      final v = topicInfo;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['topicInfo'] = arr0;
    }
    return data;
  }
}
