///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TopicModel {
/*
{
  "topicId": 1,
  "label": "breaking",
  "tag": "afghanistan",
  "description": "Follow live as the Taliban seizes territory across Afghanistan in the wake of the U.S. withdrawal.",
  "thumbImage": "taliban.jpeg",
  "status": 1,
  "noNews": 1,
  "realTime": "2021-11-18T20:40:14.945166",
  "languageId": "en"
}
*/

  int? topicId;
  String? label;
  String? tag;
  String? description;
  String? thumbImage;
  int? status;
  int? noNews;
  String? realTime;
  String? languageId;

  TopicModel({
    this.topicId,
    this.label,
    this.tag,
    this.description,
    this.thumbImage,
    this.status,
    this.noNews,
    this.realTime,
    this.languageId,
  });
  TopicModel.fromJson(Map<String, dynamic> json) {
    topicId = json['topicId']?.toInt();
    label = json['label']?.toString();
    tag = json['tag']?.toString();
    description = json['description']?.toString();
    thumbImage = json['thumbImage']?.toString();
    status = json['status']?.toInt();
    noNews = json['noNews']?.toInt();
    realTime = json['realTime']?.toString();
    languageId = json['languageId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['topicId'] = topicId;
    data['label'] = label;
    data['tag'] = tag;
    data['description'] = description;
    data['thumbImage'] = thumbImage;
    data['status'] = status;
    data['noNews'] = noNews;
    data['realTime'] = realTime;
    data['languageId'] = languageId;
    return data;
  }
}
