///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NewsCommunityModelPublisher {
/*
{
  "userId": "69db714f-9576-45ba-b5b7-f00649be03de",
  "fullName": "Le Xuan Thành",
  "phoneNumber": null,
  "userName": "LXthanh",
  "email": "thanh26092000@gmail.com",
  "status": 1,
  "avatar": null,
  "noNewsContributed": 2,
  "roles": null
}
*/

  String? userId;
  String? fullName;
  String? phoneNumber;
  String? userName;
  String? email;
  int? status;
  String? avatar;
  int? noNewsContributed;
  String? roles;

  NewsCommunityModelPublisher({
    this.userId,
    this.fullName,
    this.phoneNumber,
    this.userName,
    this.email,
    this.status,
    this.avatar,
    this.noNewsContributed,
    this.roles,
  });
  NewsCommunityModelPublisher.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    fullName = json['fullName']?.toString();
    phoneNumber = json['phoneNumber']?.toString();
    userName = json['userName']?.toString();
    email = json['email']?.toString();
    status = json['status']?.toInt();
    avatar = json['avatar']?.toString();
    noNewsContributed = json['noNewsContributed']?.toInt();
    roles = json['roles']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['fullName'] = fullName;
    data['phoneNumber'] = phoneNumber;
    data['userName'] = userName;
    data['email'] = email;
    data['status'] = status;
    data['avatar'] = avatar;
    data['noNewsContributed'] = noNewsContributed;
    data['roles'] = roles;
    return data;
  }
}

class NewsCommunityModel {
/*
{
  "newsCommunityId": 1,
  "title": "test",
  "content": "test",
  "isPopular": true,
  "publisher": {
    "userId": "69db714f-9576-45ba-b5b7-f00649be03de",
    "fullName": "Le Xuan Thanh",
    "phoneNumber": null,
    "userName": "Lxthanh",
    "email": "thanh26092000@gmail.com",
    "status": 1,
    "avatar": null,
    "noNewsContributed": 2,
    "roles": null
  },
  "datePublished": "2021-04-12T00:00:00",
  "thumbNews": null,
  "languageId": "vi"
}
*/

  int? newsCommunityId;
  String? title;
  String? content;
  bool? isPopular;
  NewsCommunityModelPublisher? publisher;
  String? datePublished;
  String? thumbNews;
  String? languageId;

  NewsCommunityModel({
    this.newsCommunityId,
    this.title,
    this.content,
    this.isPopular,
    this.publisher,
    this.datePublished,
    this.thumbNews,
    this.languageId,
  });
  NewsCommunityModel.fromJson(Map<String, dynamic> json) {
    newsCommunityId = json['newsCommunityId']?.toInt();
    title = json['title']?.toString();
    content = json['content']?.toString();
    isPopular = json['isPopular'];
    publisher = (json['publisher'] != null)
        ? NewsCommunityModelPublisher.fromJson(json['publisher'])
        : null;
    datePublished = json['datePublished']?.toString();
    thumbNews = json['thumbNews']?.toString();
    languageId = json['languageId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['newsCommunityId'] = newsCommunityId;
    data['title'] = title;
    data['content'] = content;
    data['isPopular'] = isPopular;
    if (publisher != null) {
      data['publisher'] = publisher!.toJson();
    }
    data['datePublished'] = datePublished;
    data['thumbNews'] = thumbNews;
    data['languageId'] = languageId;
    return data;
  }
}
