///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserModel {
/*
{
  "userId": "69db714f-9576-45ba-b5b7-f00649be03de",
  "fullName": "Huynh Huu Khanh",
  "userName": "hkhansh27",
  "email": "khanh200111@gmail.com",
  "status": 1,
  "avatar": null,
  "noNewsVoted": null,
  "noNewsContributed": null,
  "roles": [
    "Admin"
  ]
}
*/

  String? userId;
  String? fullName;
  String? userName;
  String? email;
  int? status;
  String? avatar;
  String? noNewsVoted;
  String? noNewsContributed;
  List<String?>? roles;

  UserModel({
    this.userId,
    this.fullName,
    this.userName,
    this.email,
    this.status,
    this.avatar,
    this.noNewsVoted,
    this.noNewsContributed,
    this.roles,
  });
  UserModel.fromJson(Map<String, dynamic> json) {
    userId = json['userId']?.toString();
    fullName = json['fullName']?.toString();
    userName = json['userName']?.toString();
    email = json['email']?.toString();
    status = json['status']?.toInt();
    avatar = json['avatar']?.toString();
    noNewsVoted = json['noNewsVoted']?.toString();
    noNewsContributed = json['noNewsContributed']?.toString();
    if (json['roles'] != null) {
      final v = json['roles'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      roles = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['fullName'] = fullName;
    data['userName'] = userName;
    data['email'] = email;
    data['status'] = status;
    data['avatar'] = avatar;
    data['noNewsVoted'] = noNewsVoted;
    data['noNewsContributed'] = noNewsContributed;
    if (roles != null) {
      final v = roles;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['roles'] = arr0;
    }
    return data;
  }
}
